# Generated by Django 4.2.6 on 2023-10-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(max_length=300)),
                ('aula', models.SmallIntegerField(max_length=4)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.SmallIntegerField(max_length=1)),
            ],
        ),
    ]
