# Generated by Django 4.2.6 on 2023-10-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estado',
            field=models.SmallIntegerField(),
        ),
    ]
