# Generated by Django 4.2.6 on 2023-10-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
