# Generated by Django 4.2.6 on 2023-10-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_delete_estudiantes_alter_cursos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
