# Generated by Django 4.2.6 on 2023-10-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_alter_cursos_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estado',
            field=models.SmallIntegerField(),
        ),
    ]
