# Generated by Django 4.2.6 on 2023-10-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_cursos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='estado',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
